title: Fluppisoft
description: >-
  Fluppisoft is the independent German developer and publisher of Brick Rigs, the creative physics sandbox game.
lang: en
logo: /assets/images/fluppisoft-logo.svg
baseurl: ""
url: "https://fluppisoft.com"

theme: minima

plugins:
  - jekyll-feed

minima:
  skin: dark
  social_links:
    - platform: instagram
      title: Instagram
      user_url: https://instagram.fluppisoft.com/
    - platform: tiktok
      title: TikTok
      user_url: https://www.tiktok.com/@fluppisoft
    - platform: youtube
      title: YouTube
      user_url: https://www.youtube.com/@FluppisoftGmbH

header_pages:
  - index.md
  - brick-rigs/index.md
  - blog.md
  - imprint.md

permalink: /blog/:title/

exclude:
  - README.md
  - .gitignore
  - python/
