title: Fluppisoft
description: >-
  Welcome to Fluppisoft, a game developer from Bavaria.
baseurl: ""
url: "https://fluppisoft.com"

theme: minima

plugins:
- jekyll-feed

minima:
  skin: dark
  social_links:
  - { platform: instagram, title: Instagram, user_url: "https://instagram.fluppisoft.com/" }
  - { platform: twitter, title: Twitter, user_url: "https://twitter.fluppisoft.com/" }

header_pages:
- index.md
- brick-rigs/index.md
- blog.md
- imprint.md

permalink: /blog/:title/

exclude:
- README.md
- .gitignore
- python/
